import{A as d,S as u,i as p,a as f}from"./assets/vendor-40e976df.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const b=document.querySelector(".faq-list"),m=document.querySelectorAll(".ac");new d(b,{openOnInit:[0],collapse:!0,duration:400,showMultiple:!1,beforeOpen:function(r){r.previousElementSibling&&r.previousElementSibling.classList.add("no-border-bottom"),r.classList.add("no-border-bottom")},beforeClose:function(){m.forEach(r=>{r.classList.remove("no-border-bottom")})}});const l=document.querySelector(".mySwiper"),i=document.querySelector(".s-button-next"),n=document.querySelector(".s-button-prev"),w=()=>{p.error({title:"Error",message:"Sorry, there are problems on the server",position:"topRight",timeout:3e3})};async function v(){return(await f.get("https://portfolio-js.b.goit.study/api/reviews")).data}async function y(){try{let o=function(e){const t=e.map(s=>`<li class="swiper-item swiper-slide">
            <p class="text-review">${s.review}</p>
            <div class="reviewer">
              <img src="${s.avatar_url}" alt="${s.author}" class="reviewer-foto" />
              <p class="reviewer-name">${s.author}</p>
            </div>
          </li>`).join("");l.innerHTML="",l.insertAdjacentHTML("beforeend",t)},c=function(){a.isEnd?(i.classList.add("disabled"),i.setAttribute("disabled","true")):(i.classList.remove("disabled"),i.removeAttribute("disabled")),a.isBeginning?(n.classList.add("disabled"),n.setAttribute("disabled","true")):(n.classList.remove("disabled"),n.removeAttribute("disabled"))};const r=await v();o(r);const a=new u(".swiper",{navigation:{nextEl:".s-button-next",prevEl:".s-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0,pageUpDown:!0},mousewheel:{sensitivity:3},breakpoints:{300:{slidesPerView:1,spaceBetween:0},1280:{slidesPerView:2,spaceBetween:32}}});c(),a.on("slideChange",c)}catch(r){w();const o=`<li class="swiper-item swiper-slide">
                     <p class="text-review error">Not found</p>`;l.insertAdjacentHTML("beforeend",o),i.classList.add("disabled"),n.classList.add("disabled"),n.setAttribute("disabled","true"),i.setAttribute("disabled","true"),console.error("Error fetching reviews:",r)}}y();
//# sourceMappingURL=commonHelpers.js.map
